"""Constants for the MIMO ASR integration."""
DOMAIN = "mimo_asr"
CONF_API_KEY = "api_key"
CONF_BASE_URL = "base_url"
DEFAULT_BASE_URL = "https://api.xiaomimimo.com/v1"
CONF_LANGUAGE = "language"
DEFAULT_LANGUAGE = "zh"
CONF_MODEL = "model"
DEFAULT_MODEL = "mimo-v2.5-asr"
